version: '3.6'

services:
  front_end:
    build:
      context: './'
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      NODE_ENV: production
    ports:
      - '3000:3000'
